### ISSUE TITLE
Authenticating the calls between 2 Azure functions

### ISSUE THREAD

**Issue by sdg002** [kuromukira/azure-functions-jwt-validation-extension#4]
Hi,
Consider the following scenario:
- I have two HTTP trigger functions in 2 different Function Apps - **Func1** and **Func2** 
- Both **Func1** and **Func2** are called by public users . The caller is authenticated by Firebase login/password and then a bearer token is sent across to Func1 and Func2.

If **Func1** wants to make a call to **Func2** then what approach should **Func2** take to authenticate itself to **Func1** so that **Func1** can seamlessly handle both public users and internal calls?

Thank you

**Comment by kuromukira** [comment]
Hi @sdg002 ,

I think you need something in between to make the interaction easier. Here's what I think:
I'll assume Func2 is calling an internal service/repo/factory/etc to execute it's logic. Func1 and Func2 are both http triggers.

- The Function App where Func2 belongs in should also have another Func that exposes the same service/repo/factory method but uses Function Keys as authentication. Let's call this Func2a
- Func1, when needed to, can call Func2a and use Function Keys

or

- Or you can just call Func2 from Func1 like a normal http request via orchestration (durable functions). But you need to pass the token you receive from Func1 down to Func2

🍻

**Comment by sdg002** [comment]
Thank you
