### ISSUE TITLE
Not Able to Validate Token Getting below error

### ISSUE THREAD

**Issue by vinyyoo** [kuromukira/azure-functions-jwt-validation-extension#5]
'IDX10503: Signature validation failed. Token does not have a kid. Keys tried: 'System.Text.StringBuilder'.
Exceptions caught:
 'System.Text.StringBuilder'.
token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.'

Can you please help here to solve the issue 

I think 
SecurityKey[] keys = x509Data.Values.Select(CreateSecurityKeyFromPublicKey).ToArray(); because of this line we are getting error

**Comment by kuromukira** [comment]
Hi @vinyyoo ,

Can you please give a more detailed error log for that line? Are you also using Firebase Auth?
